on:
  push:
    branches:
      - master
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: 🏗 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm
          cache-dependency-path: Selu383.SP24.Mobile/package-lock.json

      - name: 🏗 Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          project: Selu383.SP24.Mobile
          packager: npm

      - name: 📦 Install dependencies
        run: npm install ./Selu383.SP24.Mobile

      - name: set environment variables
        uses: allenevans/set-env@v3.0.0
        with:
          EAS_LOCAL_BUILD_ARTIFACTS_DIR: ${{ runner.temp }}

      - name: 🚀 Build app
        run: cd ./Selu383.SP24.Mobile/ && eas build -p android --non-interactive --local

      - name: 🛳️ Make Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          files: |
            ${{ runner.temp }}/*.apk
